//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int id { get; set; }
        public string subj { get; set; }
        public string descr { get; set; }
        public int createdby { get; set; }
        public Nullable<int> assignedto { get; set; }
        public string created_by_name { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
